name: Latest blog post workflow
on: 
    schedule:
        #triggers the workflow every day at 5:30 and 17:30 UTC
        - cron: '30 5,20 * * *'
jobs: 
    update-readme-with-blog: 
        name: Update this repo's README with latest blog posts
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v2
            - uses: gautamkrishnar/blog-post-workflow@master
              with: 
                max_post_count: "10"
                feed_list: "https://medium.com/feed/@boottechnologies-ci"
